{
 "title": "open-mission",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "아이템 성공률 (5m) (success 사용)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(item_create_duration_seconds_count{success=\"true\"}[5m]))\n/\nsum(rate(item_create_duration_seconds_count[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "아이템 생성 (성공 , 실패 ) (success 라벨 사용)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(\n  increase(item_create_duration_seconds_count{success=\"true\"}[5m])\n)",
     "legendFormat": "item 성공 횟수"
    },
    {
     "expr": "sum(\n  increase(item_create_duration_seconds_count{success=\"false\"}[5m])\n)",
     "legendFormat": "item 실패 횟수"
    }
   ]
  },
  {
   "title": "최근 10분 동안 Item 생성 시도 수",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum(\n  increase(item_create_attempt_total[10m])\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP Success Rate (5m)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "1 - (\n  sum(rate(http_server_requests_seconds_count{status=~\"5..\"}[5m]))\n  /\n  sum(rate(http_server_requests_seconds_count[5m]))\n)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Process CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    { "expr": "process_cpu_usage", "legendFormat": "cpu 사용량" }
   ]
  },
  {
   "title": "JVM Heap Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{area=\"heap\"})\n/\nsum(jvm_memory_max_bytes{area=\"heap\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP p95 latency (5m)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(\n  0.95,\n  sum(\n    rate(http_server_requests_seconds_bucket{\n      uri!~\"/actuator.*\"\n    }[5m])\n  ) by (le)\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP 5xx Error Rate (5m)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(\n  rate(http_server_requests_seconds_count{\n    status=~\"5..\",\n    uri!~\"/actuator.*\"\n  }[5m])\n)\n/ \nsum(\n  rate(http_server_requests_seconds_count{\n    uri!~\"/actuator.*\"\n  }[5m])\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP Requests per Minute (5m)",
   "type": "timeseries",
   "description": "분당 요청수",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
   "targets": [
    {
     "expr": "sum(\n  increase(http_server_requests_seconds_count{uri!~\"/actuator.*\"}[5m])\n)",
     "legendFormat": "Reqeust per Minute"
    }
   ]
  }
 ]
}